/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const YndlingsserierLazyImport = createFileRoute('/yndlingsserier')()
const RealityLazyImport = createFileRoute('/reality')()
const Projekt1LazyImport = createFileRoute('/projekt1')()
const IndkoebLazyImport = createFileRoute('/indkoeb')()
const HundeLazyImport = createFileRoute('/hunde')()
const GaesterLazyImport = createFileRoute('/gaester')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const YndlingsserierLazyRoute = YndlingsserierLazyImport.update({
  path: '/yndlingsserier',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/yndlingsserier.lazy').then((d) => d.Route),
)

const RealityLazyRoute = RealityLazyImport.update({
  path: '/reality',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/reality.lazy').then((d) => d.Route))

const Projekt1LazyRoute = Projekt1LazyImport.update({
  path: '/projekt1',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/projekt1.lazy').then((d) => d.Route))

const IndkoebLazyRoute = IndkoebLazyImport.update({
  path: '/indkoeb',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/indkoeb.lazy').then((d) => d.Route))

const HundeLazyRoute = HundeLazyImport.update({
  path: '/hunde',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/hunde.lazy').then((d) => d.Route))

const GaesterLazyRoute = GaesterLazyImport.update({
  path: '/gaester',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/gaester.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/gaester': {
      preLoaderRoute: typeof GaesterLazyImport
      parentRoute: typeof rootRoute
    }
    '/hunde': {
      preLoaderRoute: typeof HundeLazyImport
      parentRoute: typeof rootRoute
    }
    '/indkoeb': {
      preLoaderRoute: typeof IndkoebLazyImport
      parentRoute: typeof rootRoute
    }
    '/projekt1': {
      preLoaderRoute: typeof Projekt1LazyImport
      parentRoute: typeof rootRoute
    }
    '/reality': {
      preLoaderRoute: typeof RealityLazyImport
      parentRoute: typeof rootRoute
    }
    '/yndlingsserier': {
      preLoaderRoute: typeof YndlingsserierLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  GaesterLazyRoute,
  HundeLazyRoute,
  IndkoebLazyRoute,
  Projekt1LazyRoute,
  RealityLazyRoute,
  YndlingsserierLazyRoute,
])

/* prettier-ignore-end */
