/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SqlblocksLazyImport = createFileRoute('/sqlblocks')()
const SqlblocksIndexLazyImport = createFileRoute('/sqlblocks/')()
const SqlblocksYndlingsserierLazyImport = createFileRoute(
  '/sqlblocks/yndlingsserier',
)()
const SqlblocksRealityLazyImport = createFileRoute('/sqlblocks/reality')()
const SqlblocksProjekt1LazyImport = createFileRoute('/sqlblocks/projekt1')()
const SqlblocksHundeLazyImport = createFileRoute('/sqlblocks/hunde')()
const SqlblocksGaesterLazyImport = createFileRoute('/sqlblocks/gaester')()

// Create/Update Routes

const SqlblocksLazyRoute = SqlblocksLazyImport.update({
  path: '/sqlblocks',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sqlblocks.lazy').then((d) => d.Route))

const SqlblocksIndexLazyRoute = SqlblocksIndexLazyImport.update({
  path: '/',
  getParentRoute: () => SqlblocksLazyRoute,
} as any).lazy(() =>
  import('./routes/sqlblocks.index.lazy').then((d) => d.Route),
)

const SqlblocksYndlingsserierLazyRoute =
  SqlblocksYndlingsserierLazyImport.update({
    path: '/yndlingsserier',
    getParentRoute: () => SqlblocksLazyRoute,
  } as any).lazy(() =>
    import('./routes/sqlblocks.yndlingsserier.lazy').then((d) => d.Route),
  )

const SqlblocksRealityLazyRoute = SqlblocksRealityLazyImport.update({
  path: '/reality',
  getParentRoute: () => SqlblocksLazyRoute,
} as any).lazy(() =>
  import('./routes/sqlblocks.reality.lazy').then((d) => d.Route),
)

const SqlblocksProjekt1LazyRoute = SqlblocksProjekt1LazyImport.update({
  path: '/projekt1',
  getParentRoute: () => SqlblocksLazyRoute,
} as any).lazy(() =>
  import('./routes/sqlblocks.projekt1.lazy').then((d) => d.Route),
)

const SqlblocksHundeLazyRoute = SqlblocksHundeLazyImport.update({
  path: '/hunde',
  getParentRoute: () => SqlblocksLazyRoute,
} as any).lazy(() =>
  import('./routes/sqlblocks.hunde.lazy').then((d) => d.Route),
)

const SqlblocksGaesterLazyRoute = SqlblocksGaesterLazyImport.update({
  path: '/gaester',
  getParentRoute: () => SqlblocksLazyRoute,
} as any).lazy(() =>
  import('./routes/sqlblocks.gaester.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sqlblocks': {
      preLoaderRoute: typeof SqlblocksLazyImport
      parentRoute: typeof rootRoute
    }
    '/sqlblocks/gaester': {
      preLoaderRoute: typeof SqlblocksGaesterLazyImport
      parentRoute: typeof SqlblocksLazyImport
    }
    '/sqlblocks/hunde': {
      preLoaderRoute: typeof SqlblocksHundeLazyImport
      parentRoute: typeof SqlblocksLazyImport
    }
    '/sqlblocks/projekt1': {
      preLoaderRoute: typeof SqlblocksProjekt1LazyImport
      parentRoute: typeof SqlblocksLazyImport
    }
    '/sqlblocks/reality': {
      preLoaderRoute: typeof SqlblocksRealityLazyImport
      parentRoute: typeof SqlblocksLazyImport
    }
    '/sqlblocks/yndlingsserier': {
      preLoaderRoute: typeof SqlblocksYndlingsserierLazyImport
      parentRoute: typeof SqlblocksLazyImport
    }
    '/sqlblocks/': {
      preLoaderRoute: typeof SqlblocksIndexLazyImport
      parentRoute: typeof SqlblocksLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  SqlblocksLazyRoute.addChildren([
    SqlblocksGaesterLazyRoute,
    SqlblocksHundeLazyRoute,
    SqlblocksProjekt1LazyRoute,
    SqlblocksRealityLazyRoute,
    SqlblocksYndlingsserierLazyRoute,
    SqlblocksIndexLazyRoute,
  ]),
])

/* prettier-ignore-end */
